services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABSAE: 'shop'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql